1.0 Designed the database schema. Configured SpringBoot project.
POOSTOTEL/EventHub-IntexSoft-Project pull request #1
Opened 2024-01-16 23:03 UTC by POOSTOTEL

Added liquibase support. Created basic entities.

2024-01-17 15:00 UTC, archiac requested changes

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/ServletInitializer.java
>  import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
что это за класс? думаю можно выпилить

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/controller/UserController.java
> +@RequiredArgsConstructor
Раз уже сюда попал контроллер, то нужен RequestMapping

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/controller/UserController.java
> +    public List<User> allUsers() {
обернем ResponseEntity и лучше выбрать другое название метода

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/entity/Comment.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Почему такая стратегия?

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/entity/Comment.java
> +public class Comment implements Serializable {
не будем использовать Serializable, выпиливаем по всех сущностях

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/repository/UserRepository.java
> +    List<User> findAllBy();
findAllBy  By что? обычно используют findAll, а findByName и уже понятно что ты ищешь по Name

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/resources/db/changelog/db.changelog-master.xml
> +    <changeSet id="1" author="postgres">
в id обычно пишут "Creating table USERS" и в author укажи себя
Обязательно добавь preConditions на создание таблиц

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/resources/db/changelog/db.changelog-master.xml
> +        <createTable tableName="Users">
добавь сюда параметр remarks, в котором описывает что за таблица, иногда непонятно

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/resources/db/changelog/db.changelog-master.xml
> +            <column name="user_id" type="int" autoIncrement="true">
remarks аналогично на каждую колонку с ее описанием
добавь параметр primaryKeyName

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/UserService.java
> +    public List<User> getAllUsers() {
Мы не можем напрямую взять сущность из БД и отдать, нужно сконвертить ее в DTO и обратный механизм, когда приходит что-то в апишку и надо сохранить в БД то DTO конвертим в сущность

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/resources/db/changelog/db.changelog-master.xml
> +            <column name="email" type="varchar(50)">
если у нас user_name то уже лучше тогда сделать, user_email и с паролем

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/resources/db/changelog/db.changelog-master.xml
> +            <column name="rating" type="int">
что за рейтинг? и как он рассчитывается?

2024-01-17 15:00 UTC, archiac commented on EventHub-IntexSoft/src/main/resources/db/changelog/db.changelog-master.yaml
> +databaseChangeLog:
это чисто так для себя потрениться?

2024-01-17 16:46 UTC, POOSTOTEL commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/ServletInitializer.java
>  import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
Я уже говорил, что он создался автоматически SpringInitializer-ом, но я попробую его удалить.

2024-01-17 16:50 UTC, POOSTOTEL commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/controller/UserController.java
> +@RequiredArgsConstructor
Хорошо, я добавлю глобальный RequestMapping, просто я добавил аннотацию @RestController и задал @GetMapping напрямую по адресу "user/all", а мог создать @RequestMapping("user/") и дальше уже над самим методом @GetMapping("all/").

2024-01-17 16:50 UTC, POOSTOTEL commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/controller/UserController.java
> +    public List<User> allUsers() {
Можешь пожалуйста объяснить что значит "Обернём ResponseEntity"...? Название метода изменю!

2024-01-17 16:52 UTC, POOSTOTEL commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/entity/Comment.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Потому что она позволяет отслеживать чёткую иерархию в нумерации айдишников записей в таблице, на сколько я знаю, всех способов генерации существует 4, я почитаю про все из них и подберу наиболее подходящий.

2024-01-17 16:53 UTC, POOSTOTEL commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/entity/Comment.java
> +public class Comment implements Serializable {
Хорошо, удалю весь Serializable.

2024-01-17 16:54 UTC, POOSTOTEL commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/UserService.java
> +    public List<User> getAllUsers() {
Добавлю для всех сущностей DTO.

2024-01-17 16:56 UTC, POOSTOTEL commented on EventHub-IntexSoft/src/main/resources/db/changelog/db.changelog-master.xml
> +            <column name="rating" type="int">
Пользователь после завершения ивента сможет ставить оценку от 1 до 10, эта оценка будет влиять на рейтинг организатора.

2024-01-17 16:56 UTC, POOSTOTEL commented on EventHub-IntexSoft/src/main/resources/db/changelog/db.changelog-master.yaml
> +databaseChangeLog:
Да, я знакомился со всеми типами файлов параметризации liquibase.

2024-01-18 17:07 UTC, archiac requested changes

2024-01-18 17:07 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/DTO/CommentDTO.java
> +public class CommentDTO {
А давай  все DTO сделаем с помощью MapStruct, заодно познакомишься с ним

2024-01-18 17:07 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/entity/Comment.java
>      @ManyToOne
Хочешь сразу, чтобы затягивались Ивенты? Почитай про FetchType и подумай какой лучше когда и где применять

2024-01-18 17:07 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/UserService.java
> +        for (User user : userRepository.findAll()) {
Ну тут поменяется логика когда прикрутим MapStruct, давай еще будем использовать Optional

2024-01-18 17:07 UTC, archiac commented on EventHub-IntexSoft/src/main/resources/db/changelog/db.changelog-master.xml
> +    <changeSet id="Inserting into users table" author="poostotel">
Insert будем выносить в отдельный changelog, этот будет использоваться чисто для создания таблиц и переименуй, чтобы было понятно что он для создания таблиц

2024-01-22 15:36 UTC, archiac requested changes

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/controller/EventController.java
> +    public ResponseEntity<Optional<EventDto>> getEvent(@PathVariable("id") Long id) {
лучше назвать getById и возвращаем без Optional

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/controller/EventController.java
> +    public ResponseEntity<Optional<EventDto>> updateEvent(@RequestBody Event event) {
из контроллера возвращаем EventDto, без Optional

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/controller/EventController.java
> +    @GetMapping("/delete/{id}")
DeleteMapping

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/EventService.java
> +    public Optional<EventDto> getEvent(Long id) {
getEventById

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/EventService.java
> +    public void deleteEvent(Long id) {
Если тут подразумевается логика, что когда удаляется событие, то удаляются комменты и участники
то на сущность Event нужно добавить Cascade. и указать нужный тип( почитай и разберись какие есть)

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/EventService.java
> +    public void deleteEvent(Long id) {
и deleteEventById, удаляем же тоже по ID

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/EventService.java
> +    public Optional<EventDto> updateEvent(Event event) {
почитай как работает update в hibernate, думаю можно найти более изящное решение

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/EventService.java
> +    public void deleteEvent(Long id) {
а если у нас не будет такого события, что будет?

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/UserService.java
> +    public Optional<UserDto> getUser(Long id) {
byId

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/UserService.java
> +    public void deleteUser(Long id) {
аналогичная логика с Ивент сервисом

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/controller/EventController.java
> +    public ResponseEntity<Optional<EventDto>> getEvent(@PathVariable("id") Long id) {
А если не найдет такого события?

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/controller/EventController.java
> +    @GetMapping("/delete/{id}")
а если не будет такого события?

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/controller/UserController.java
> +    public ResponseEntity<Optional<UserDto>> getUser(@PathVariable("id") Long id) {
Аналогично

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/controller/UserController.java
> +    @GetMapping("/delete/{id}")
DeleteMapping и по аналогии с комментариями выше

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/mapper/CommentMapper.java
> +
пустые строки

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/mapper/EventMapper.java
> +
тоже

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/mapper/ParticipantMapper.java
> +
тоже

2024-01-22 15:36 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/UserService.java
> +    @Transactional
Почему тут повесил?

2024-01-22 15:41 UTC, POOSTOTEL commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/UserService.java
> +    @Transactional
Потому что Hibernate обязал заключить операцию удаления в транзакцию, наверное лучше вложить аннотацию внутрь метода.

2024-01-23 16:39 UTC, archiac requested changes

2024-01-23 16:39 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/DTO/CommentDto.java
> +  private Long id;
лучше заменим везде id на названиеСущностиId

2024-01-23 16:39 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/controller/CommentController.java
> +public class CommentController {
Забыл порефакторить этот контроллер

2024-01-23 16:39 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/entity/Participant.java
> +  @ManyToOne(cascade = CascadeType.REMOVE, fetch = FetchType.EAGER)
ManyToOne вроде и так по дефолту EAGER

2024-01-23 16:39 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/Impl/UserServiceImpl.java
> +  @Transactional(propagation = Propagation.REQUIRED, isolation = Isolation.READ_COMMITTED)
Propagation.REQUIRED это и так дефолтной значение

2024-01-24 13:19 UTC, archiac requested changes

2024-01-24 13:19 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/Impl/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
Код стайл

2024-01-24 13:19 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/Impl/EventServiceImpl.java
> +public class EventServiceImpl implements EventService {
Код стайл

2024-01-24 13:19 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/Impl/ParticipantServiceImpl.java
> +public class ParticipantServiceImpl implements ParticipantService {
Код стайл

2024-01-24 13:19 UTC, archiac commented on EventHub-IntexSoft/src/main/java/com/Eventhub/EventHubIntexSoft/service/Impl/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
что-то кажется что тут тоже поехал код стайл

2024-01-25 07:10 UTC, merged